package:
  name: teachopencadd
  version: "1.3.0"

source:
  git_url: ../../

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python
  entry_points:
    - teachopencadd = teachopencadd.cli:main

requirements:
  host:
    - python
    - pip
  run:
    # General dependencies
    - python>=3.6
    - jupyter
    - jupyterlab
    - ipywidgets>=7.5
    # Cheminformatics
    - rdkit>=2018.09.2.0,<2020.09.2
    - scikit-learn
    - biopandas
    - seaborn
    - pypdb 1.*
    - chembl_webresource_client
    - nglview
    - requests
    - openbabel
    - lxml
    - bravado
    - beautifulsoup4
    - biotite
    - mdanalysis
    - plip
    - biopython<=1.77
    # note there are some pip dependencies not available in conda yet!
    # check /environment.yml for details

test:
  requires:
    - pip
  imports:
    - teachopencadd
  commands:
    - teachopencadd

about:
  home: https://github.com/volkamerlab/TeachOpenCADD
  license: CC-BY-4.0
  license_family: CC
  license_file: LICENSE
  summary: A teaching platform for computer-aided drug design (CADD) using open source packages and data
  description: |
    TeachOpenCADD is a teaching platform developed by students for students, which provides teaching
    material for central CADD topics. Since we cover both the theoretical as well as practical aspect
    of these topics, the platform addresses students and researchers with a biological/chemical as
    well as a computational background.
  doc_url: https://github.com/volkamerlab/TeachOpenCADD
  dev_url: https://github.com/volkamerlab/TeachOpenCADD

extra:
  recipe-maintainers:
    - jaimergp
    - dominiquesydow